// Auto-generated by scripts/build/generate-operation-help.mjs. Do not edit manually.
export const GENERATED_OPERATION_CATALOG = [
  {
    "name": "Documents",
    "operations": [
      "createDocument",
      "openDocument",
      "duplicateDocument",
      "saveDocument",
      "saveDocumentAs",
      "closeDocument",
      "resizeImage",
      "resizeCanvas",
      "cropDocument",
      "trimDocument",
      "rotateDocument",
      "flattenDocument",
      "mergeVisible"
    ]
  },
  {
    "name": "Layers and grouping",
    "operations": [
      "createLayer",
      "createPixelLayer",
      "createGroup",
      "groupLayers",
      "ungroupLayer",
      "deleteLayer",
      "renameLayer",
      "duplicateLayer",
      "selectLayer",
      "selectLayers",
      "moveLayer",
      "setLayerVisibility",
      "showLayer",
      "hideLayer",
      "setLayerOpacity",
      "setBlendMode",
      "setLayerProps",
      "bringLayerToFront",
      "sendLayerToBack",
      "mergeLayer",
      "rasterizeLayer",
      "linkLayers",
      "unlinkLayer"
    ]
  },
  {
    "name": "Transform and layout",
    "operations": [
      "transformLayer",
      "alignLayers",
      "distributeLayers",
      "translateLayer",
      "scaleLayer",
      "rotateLayer",
      "flipLayer",
      "skewLayer"
    ]
  },
  {
    "name": "Assets and smart objects",
    "operations": [
      "placeAsset",
      "convertToSmartObject",
      "replaceSmartObject",
      "relinkSmartObject",
      "editSmartObject"
    ]
  },
  {
    "name": "Selection and masks",
    "operations": [
      "selectAll",
      "deselect",
      "inverseSelection",
      "featherSelection",
      "expandSelection",
      "contractSelection",
      "growSelection",
      "smoothSelection",
      "selectRectangle",
      "selectEllipse",
      "selectPolygon",
      "selectLayerPixels",
      "setSelection",
      "modifySelection",
      "createLayerMask",
      "deleteLayerMask",
      "applyLayerMask"
    ]
  },
  {
    "name": "Text and shapes",
    "operations": [
      "createTextLayer",
      "setText",
      "setTextStyle",
      "createShapeLayer"
    ]
  },
  {
    "name": "Adjustments and filters",
    "operations": [
      "createAdjustmentLayer",
      "applyFilter",
      "applyGaussianBlur",
      "applyUnsharpMask",
      "applySharpen",
      "applyBlur"
    ]
  },
  {
    "name": "Export and low-level actions",
    "operations": [
      "export",
      "exportDocument",
      "exportLayer",
      "exportLayersByName",
      "batchPlay"
    ]
  }
] as const;

export const GENERATED_OPERATION_ENTRIES = [
  {
    "name": "createDocument",
    "aliases": [
      "doc.create",
      "document.create",
      "newDocument"
    ],
    "required": "None",
    "supportedArgs": "`depth`, `fill`, `height`, `mode`, `name`, `preset`, `profile`, `resolution`, `width`",
    "example": "{\n  \"op\": \"createDocument\",\n  \"name\": \"New Doc\",\n  \"width\": 1080,\n  \"height\": 1080,\n  \"resolution\": 72,\n  \"mode\": \"rgbColor\"\n}"
  },
  {
    "name": "openDocument",
    "aliases": [
      "doc.open",
      "document.open"
    ],
    "required": "`input (or path/source)`",
    "supportedArgs": "`input`, `path`, `source`",
    "example": "{\n  \"op\": \"openDocument\",\n  \"input\": \"./assets/source.psd\"\n}"
  },
  {
    "name": "duplicateDocument",
    "aliases": [
      "doc.duplicate",
      "document.duplicate"
    ],
    "required": "None",
    "supportedArgs": "`docRef`, `mergeLayersOnly`, `name`, `target`",
    "example": "{\n  \"op\": \"duplicateDocument\",\n  \"name\": \"Variant A\"\n}"
  },
  {
    "name": "saveDocument",
    "aliases": [
      "doc.save",
      "document.save"
    ],
    "required": "None",
    "supportedArgs": "`allowDialog`, `asCopy`, `docRef`, `options`, `output`, `quality`, `target`",
    "example": "{\n  \"op\": \"saveDocument\",\n  \"output\": \"./tmp/current.psd\"\n}"
  },
  {
    "name": "saveDocumentAs",
    "aliases": [
      "doc.saveAs",
      "document.saveAs"
    ],
    "required": "`output`",
    "supportedArgs": "`docRef`, `target`, `output`, `format`, `quality`, `asCopy`, `options`",
    "example": "{\n  \"op\": \"saveDocumentAs\",\n  \"output\": \"./tmp/output.psd\"\n}"
  },
  {
    "name": "closeDocument",
    "aliases": [
      "doc.close",
      "document.close"
    ],
    "required": "None",
    "supportedArgs": "`docRef`, `mode`, `output`, `save`, `saveChanges`, `saveOption`, `target`",
    "example": "{\n  \"op\": \"closeDocument\",\n  \"save\": false\n}"
  },
  {
    "name": "resizeImage",
    "aliases": [
      "document.resizeImage"
    ],
    "required": "`width` and/or `height`",
    "supportedArgs": "`docRef`, `height`, `resolution`, `target`, `width`",
    "example": "{\n  \"op\": \"resizeImage\",\n  \"width\": 1920,\n  \"height\": 1080,\n  \"resolution\": 72\n}"
  },
  {
    "name": "resizeCanvas",
    "aliases": [
      "document.resizeCanvas"
    ],
    "required": "`width`, `height`",
    "supportedArgs": "`anchor`, `docRef`, `height`, `target`, `width`",
    "example": "{\n  \"op\": \"resizeCanvas\",\n  \"width\": 1200,\n  \"height\": 1200,\n  \"anchor\": \"middleCenter\"\n}"
  },
  {
    "name": "cropDocument",
    "aliases": [
      "document.crop"
    ],
    "required": "`bounds {left, top, right, bottom}` (or top-level `left/top/right/bottom`)",
    "supportedArgs": "`angle`, `bounds`, `docRef`, `height`, `target`, `width`",
    "example": "{\n  \"op\": \"cropDocument\",\n  \"bounds\": {\n    \"left\": 0,\n    \"top\": 0,\n    \"right\": 1080,\n    \"bottom\": 1920\n  }\n}"
  },
  {
    "name": "trimDocument",
    "aliases": [
      "document.trim"
    ],
    "required": "None",
    "supportedArgs": "`bottom`, `docRef`, `left`, `right`, `target`, `top`, `trimType`",
    "example": "{\n  \"op\": \"trimDocument\",\n  \"trimType\": \"transparent\",\n  \"top\": true,\n  \"left\": true,\n  \"bottom\": true,\n  \"right\": true\n}"
  },
  {
    "name": "rotateDocument",
    "aliases": [
      "document.rotate"
    ],
    "required": "`angle`",
    "supportedArgs": "`anchor`, `angle`, `docRef`, `options`, `target`",
    "example": "{\n  \"op\": \"rotateDocument\",\n  \"angle\": 90\n}"
  },
  {
    "name": "flattenDocument",
    "aliases": [
      "flattenImage",
      "document.flatten"
    ],
    "required": "None",
    "supportedArgs": "`docRef`, `target`",
    "example": "{\n  \"op\": \"flattenDocument\"\n}"
  },
  {
    "name": "mergeVisible",
    "aliases": [
      "mergeVisibleLayers",
      "document.mergeVisibleLayers"
    ],
    "required": "None",
    "supportedArgs": "`docRef`, `target`",
    "example": "{\n  \"op\": \"mergeVisible\"\n}"
  },
  {
    "name": "createLayer",
    "aliases": [
      "layer.create"
    ],
    "required": "None",
    "supportedArgs": "`blendMode`, `docRef`, `fillNeutral`, `kind`, `name`, `opacity`",
    "example": "{\n  \"op\": \"createLayer\",\n  \"name\": \"Foreground\"\n}"
  },
  {
    "name": "createPixelLayer",
    "aliases": [
      "layer.createPixel"
    ],
    "required": "None",
    "supportedArgs": "`blendMode`, `docRef`, `fillNeutral`, `kind`, `name`, `opacity`",
    "example": "{\n  \"op\": \"createPixelLayer\",\n  \"name\": \"Paint\"\n}"
  },
  {
    "name": "createGroup",
    "aliases": [
      "createLayerGroup",
      "layer.createGroup"
    ],
    "required": "None",
    "supportedArgs": "`blendMode`, `docRef`, `fromLayers`, `name`, `opacity`",
    "example": "{\n  \"op\": \"createGroup\",\n  \"name\": \"Hero Group\"\n}"
  },
  {
    "name": "groupLayers",
    "aliases": [
      "layer.group"
    ],
    "required": "`targets[]`",
    "supportedArgs": "`docRef`, `name`, `targets`",
    "example": "{\n  \"op\": \"groupLayers\",\n  \"targets\": [\n    {\n      \"layerName\": \"Title\"\n    },\n    {\n      \"layerName\": \"CTA\"\n    }\n  ],\n  \"name\": \"Header Group\"\n}"
  },
  {
    "name": "ungroupLayer",
    "aliases": [
      "layer.ungroup"
    ],
    "required": "None",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"ungroupLayer\",\n  \"target\": {\n    \"layerName\": \"Header Group\"\n  }\n}"
  },
  {
    "name": "deleteLayer",
    "aliases": [
      "layer.delete"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"deleteLayer\",\n  \"target\": {\n    \"layerName\": \"Scratch\"\n  }\n}"
  },
  {
    "name": "renameLayer",
    "aliases": [
      "layer.rename"
    ],
    "required": "`target (or active layer)`, `name (or newName)`",
    "supportedArgs": "`name`",
    "example": "{\n  \"op\": \"renameLayer\",\n  \"target\": {\n    \"layerName\": \"Layer 1\"\n  },\n  \"name\": \"Hero\"\n}"
  },
  {
    "name": "duplicateLayer",
    "aliases": [
      "layer.duplicate"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`insertionLocation`, `name`, `placement`, `relativeTo`",
    "example": "{\n  \"op\": \"duplicateLayer\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"name\": \"Hero Copy\"\n}"
  },
  {
    "name": "selectLayer",
    "aliases": [
      "layer.select"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"selectLayer\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  }\n}"
  },
  {
    "name": "selectLayers",
    "aliases": [
      "layer.selectMany"
    ],
    "required": "`targets[]`",
    "supportedArgs": "`targets`",
    "example": "{\n  \"op\": \"selectLayers\",\n  \"targets\": [\n    {\n      \"layerName\": \"Hero\"\n    },\n    {\n      \"layerName\": \"CTA\"\n    }\n  ],\n  \"mode\": \"set\"\n}"
  },
  {
    "name": "moveLayer",
    "aliases": [
      "layer.move",
      "reorderLayer",
      "layer.reorder"
    ],
    "required": "`target (or active layer)`, `one of: by{x,y}, relativeTo+placement, to(front/back), or index/at`",
    "supportedArgs": "`at`, `by`, `index`, `insertLocation`, `placement`, `relativeTo`, `to`",
    "example": "{\n  \"op\": \"moveLayer\",\n  \"target\": {\n    \"layerName\": \"CTA\"\n  },\n  \"relativeTo\": {\n    \"layerName\": \"Hero\"\n  },\n  \"placement\": \"placeAfter\"\n}"
  },
  {
    "name": "setLayerVisibility",
    "aliases": [
      "layer.visibility"
    ],
    "required": "`target (or active layer)`, `visible`",
    "supportedArgs": "`visible`",
    "example": "{\n  \"op\": \"setLayerVisibility\",\n  \"target\": {\n    \"layerName\": \"CTA\"\n  },\n  \"visible\": true\n}"
  },
  {
    "name": "showLayer",
    "aliases": [
      "layer.show"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"showLayer\",\n  \"target\": {\n    \"layerName\": \"CTA\"\n  }\n}"
  },
  {
    "name": "hideLayer",
    "aliases": [
      "layer.hide"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"hideLayer\",\n  \"target\": {\n    \"layerName\": \"CTA\"\n  }\n}"
  },
  {
    "name": "setLayerOpacity",
    "aliases": [
      "layer.opacity"
    ],
    "required": "`target (or active layer)`, `opacity`",
    "supportedArgs": "`opacity`",
    "example": "{\n  \"op\": \"setLayerOpacity\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"opacity\": 80\n}"
  },
  {
    "name": "setBlendMode",
    "aliases": [
      "layer.blendMode"
    ],
    "required": "`target (or active layer)`, `blendMode`",
    "supportedArgs": "`blendMode`",
    "example": "{\n  \"op\": \"setBlendMode\",\n  \"target\": {\n    \"layerName\": \"Texture\"\n  },\n  \"blendMode\": \"multiply\"\n}"
  },
  {
    "name": "setLayerProps",
    "aliases": [
      "layer.setProps"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`blendMode`, `locked`, `opacity`, `visible`",
    "example": "{\n  \"op\": \"setLayerProps\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"visible\": true,\n  \"opacity\": 90,\n  \"blendMode\": \"normal\"\n}"
  },
  {
    "name": "bringLayerToFront",
    "aliases": [
      "layer.bringToFront"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"bringLayerToFront\",\n  \"target\": {\n    \"layerName\": \"CTA\"\n  }\n}"
  },
  {
    "name": "sendLayerToBack",
    "aliases": [
      "layer.sendToBack"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"sendLayerToBack\",\n  \"target\": {\n    \"layerName\": \"Background\"\n  }\n}"
  },
  {
    "name": "mergeLayer",
    "aliases": [
      "mergeLayers",
      "layer.merge"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`name`, `targets`",
    "example": "{\n  \"op\": \"mergeLayer\",\n  \"target\": {\n    \"layerName\": \"Overlay\"\n  }\n}"
  },
  {
    "name": "rasterizeLayer",
    "aliases": [
      "layer.rasterize"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`rasterizeType`, `targetType`",
    "example": "{\n  \"op\": \"rasterizeLayer\",\n  \"target\": {\n    \"layerName\": \"Smart Object\"\n  }\n}"
  },
  {
    "name": "linkLayers",
    "aliases": [
      "layer.link"
    ],
    "required": "`targets[]`",
    "supportedArgs": "`targets`",
    "example": "{\n  \"op\": \"linkLayers\",\n  \"targets\": [\n    {\n      \"layerName\": \"Icon\"\n    },\n    {\n      \"layerName\": \"Label\"\n    }\n  ]\n}"
  },
  {
    "name": "unlinkLayer",
    "aliases": [
      "layer.unlink"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"unlinkLayer\",\n  \"target\": {\n    \"layerName\": \"Icon\"\n  }\n}"
  },
  {
    "name": "transformLayer",
    "aliases": [
      "layer.transform"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`angle`, `angleH`, `angleV`, `axis`, `by`, `flip`, `height`, `horizontal`, `percent`, `rotate`, `scale`, `scaleX`, `scaleY`, `skewX`, `skewY`, `translate`, `vertical`, `width`, `x`, `y`",
    "example": "{\n  \"op\": \"transformLayer\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"scaleX\": 95,\n  \"scaleY\": 95,\n  \"rotate\": 2\n}"
  },
  {
    "name": "alignLayers",
    "aliases": [
      "layer.align"
    ],
    "required": "at least 2 layers via `targets[]` or current active selection",
    "supportedArgs": "`targets`, `axis`, `type`",
    "example": "{\n  \"op\": \"alignLayers\",\n  \"axis\": \"horizontalCenter\",\n  \"targets\": [\n    {\n      \"layerName\": \"Title\"\n    },\n    {\n      \"layerName\": \"CTA\"\n    }\n  ]\n}"
  },
  {
    "name": "distributeLayers",
    "aliases": [
      "layer.distribute"
    ],
    "required": "at least 3 layers via `targets[]` or current active selection",
    "supportedArgs": "`targets`, `axis`, `type`",
    "example": "{\n  \"op\": \"distributeLayers\",\n  \"axis\": \"horizontal\",\n  \"targets\": [\n    {\n      \"layerName\": \"Card 1\"\n    },\n    {\n      \"layerName\": \"Card 2\"\n    },\n    {\n      \"layerName\": \"Card 3\"\n    }\n  ]\n}"
  },
  {
    "name": "translateLayer",
    "aliases": [
      "layer.translate"
    ],
    "required": "`target (or active layer)`, `x/y or horizontal/vertical`",
    "supportedArgs": "`by`, `horizontal`, `vertical`, `x`, `y`",
    "example": "{\n  \"op\": \"translateLayer\",\n  \"target\": {\n    \"layerName\": \"Badge\"\n  },\n  \"x\": 12,\n  \"y\": -8\n}"
  },
  {
    "name": "scaleLayer",
    "aliases": [
      "layer.scale"
    ],
    "required": "`target (or active layer)`, `scaleX/scaleY or width/height or scale/percent`",
    "supportedArgs": "`anchor`, `height`, `options`, `percent`, `scale`, `scaleX`, `scaleY`, `width`",
    "example": "{\n  \"op\": \"scaleLayer\",\n  \"target\": {\n    \"layerName\": \"Logo\"\n  },\n  \"scaleX\": 120,\n  \"scaleY\": 120\n}"
  },
  {
    "name": "rotateLayer",
    "aliases": [
      "layer.rotate"
    ],
    "required": "`target (or active layer)`, `angle`",
    "supportedArgs": "`anchor`, `angle`, `options`",
    "example": "{\n  \"op\": \"rotateLayer\",\n  \"target\": {\n    \"layerName\": \"Badge\"\n  },\n  \"angle\": -12\n}"
  },
  {
    "name": "flipLayer",
    "aliases": [
      "layer.flip"
    ],
    "required": "`target (or active layer)`, `axis`",
    "supportedArgs": "`axis`",
    "example": "{\n  \"op\": \"flipLayer\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"axis\": \"horizontal\"\n}"
  },
  {
    "name": "skewLayer",
    "aliases": [
      "layer.skew"
    ],
    "required": "`target (or active layer)`, `angleH and/or angleV`",
    "supportedArgs": "`angleH`, `angleV`, `horizontal`, `options`, `vertical`",
    "example": "{\n  \"op\": \"skewLayer\",\n  \"target\": {\n    \"layerName\": \"Card\"\n  },\n  \"angleH\": 8\n}"
  },
  {
    "name": "placeAsset",
    "aliases": [
      "asset.place"
    ],
    "required": "`input (or path/source)`",
    "supportedArgs": "`input`, `linked`, `name`, `normalizePixels`, `path`, `source`, `transformOptions`",
    "example": "{\n  \"op\": \"placeAsset\",\n  \"input\": \"https://picsum.photos/seed/hero/1080/1080.jpg\",\n  \"name\": \"Hero Image\"\n}"
  },
  {
    "name": "convertToSmartObject",
    "aliases": [
      "smartObject.convert"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`preserveName`",
    "example": "{\n  \"op\": \"convertToSmartObject\",\n  \"target\": {\n    \"layerName\": \"Hero Image\"\n  }\n}"
  },
  {
    "name": "replaceSmartObject",
    "aliases": [
      "smartObject.replace"
    ],
    "required": "`target (or active layer)`, `input (or path/source)`",
    "supportedArgs": "`crop`, `input`, `pageNumber`, `path`, `preserveName`, `source`",
    "example": "{\n  \"op\": \"replaceSmartObject\",\n  \"target\": {\n    \"layerName\": \"Hero Image\"\n  },\n  \"input\": \"./assets/new-hero.jpg\"\n}"
  },
  {
    "name": "relinkSmartObject",
    "aliases": [
      "smartObject.relink"
    ],
    "required": "`target (or active layer)`, `input (or path/source)`",
    "supportedArgs": "`input`, `path`, `preserveName`, `source`",
    "example": "{\n  \"op\": \"relinkSmartObject\",\n  \"target\": {\n    \"layerName\": \"Hero Image\"\n  },\n  \"input\": \"./assets/linked-hero.psb\"\n}"
  },
  {
    "name": "editSmartObject",
    "aliases": [
      "smartObject.edit"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"editSmartObject\",\n  \"target\": {\n    \"layerName\": \"Hero Image\"\n  }\n}"
  },
  {
    "name": "selectAll",
    "aliases": [
      "selection.selectAll"
    ],
    "required": "None",
    "supportedArgs": "`docRef`",
    "example": "{\n  \"op\": \"selectAll\"\n}"
  },
  {
    "name": "deselect",
    "aliases": [
      "selection.deselect"
    ],
    "required": "None",
    "supportedArgs": "`docRef`",
    "example": "{\n  \"op\": \"deselect\"\n}"
  },
  {
    "name": "inverseSelection",
    "aliases": [
      "invertSelection",
      "selection.inverse"
    ],
    "required": "None",
    "supportedArgs": "`docRef`",
    "example": "{\n  \"op\": \"inverseSelection\"\n}"
  },
  {
    "name": "featherSelection",
    "aliases": [
      "selection.feather"
    ],
    "required": "`by or radius`",
    "supportedArgs": "`applyEffectAtCanvasBounds`, `by`, `docRef`, `radius`",
    "example": "{\n  \"op\": \"featherSelection\",\n  \"radius\": 8\n}"
  },
  {
    "name": "expandSelection",
    "aliases": [
      "selection.expand"
    ],
    "required": "`by`",
    "supportedArgs": "`applyEffectAtCanvasBounds`, `by`, `docRef`",
    "example": "{\n  \"op\": \"expandSelection\",\n  \"by\": 12\n}"
  },
  {
    "name": "contractSelection",
    "aliases": [
      "selection.contract"
    ],
    "required": "`by`",
    "supportedArgs": "`applyEffectAtCanvasBounds`, `by`, `docRef`",
    "example": "{\n  \"op\": \"contractSelection\",\n  \"by\": 8\n}"
  },
  {
    "name": "growSelection",
    "aliases": [
      "selection.grow"
    ],
    "required": "`by or tolerance`",
    "supportedArgs": "`by`, `docRef`, `tolerance`",
    "example": "{\n  \"op\": \"growSelection\",\n  \"tolerance\": 32\n}"
  },
  {
    "name": "smoothSelection",
    "aliases": [
      "selection.smooth"
    ],
    "required": "`radius`",
    "supportedArgs": "`applyEffectAtCanvasBounds`, `docRef`, `radius`",
    "example": "{\n  \"op\": \"smoothSelection\",\n  \"radius\": 6\n}"
  },
  {
    "name": "selectRectangle",
    "aliases": [
      "selection.selectRectangle"
    ],
    "required": "`bounds {left,top,right,bottom}`",
    "supportedArgs": "`antiAlias`, `bounds`, `docRef`, `feather`, `mode`",
    "example": "{\n  \"op\": \"selectRectangle\",\n  \"bounds\": {\n    \"left\": 80,\n    \"top\": 80,\n    \"right\": 1000,\n    \"bottom\": 1400\n  },\n  \"mode\": \"replace\"\n}"
  },
  {
    "name": "selectEllipse",
    "aliases": [
      "selection.selectEllipse"
    ],
    "required": "`bounds {left,top,right,bottom}`",
    "supportedArgs": "`antiAlias`, `bounds`, `docRef`, `feather`, `mode`",
    "example": "{\n  \"op\": \"selectEllipse\",\n  \"bounds\": {\n    \"left\": 220,\n    \"top\": 260,\n    \"right\": 860,\n    \"bottom\": 900\n  },\n  \"mode\": \"replace\"\n}"
  },
  {
    "name": "selectPolygon",
    "aliases": [
      "selection.selectPolygon"
    ],
    "required": "`points[3+]`",
    "supportedArgs": "`antiAlias`, `docRef`, `feather`, `mode`, `points`",
    "example": "{\n  \"op\": \"selectPolygon\",\n  \"points\": [\n    {\n      \"x\": 100,\n      \"y\": 100\n    },\n    {\n      \"x\": 900,\n      \"y\": 120\n    },\n    {\n      \"x\": 560,\n      \"y\": 900\n    }\n  ],\n  \"mode\": \"replace\"\n}"
  },
  {
    "name": "selectLayerPixels",
    "aliases": [
      "selection.loadLayerPixels"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`docRef`, `invert`, `mode`",
    "example": "{\n  \"op\": \"selectLayerPixels\",\n  \"target\": {\n    \"layerName\": \"Logo\"\n  },\n  \"mode\": \"replace\"\n}"
  },
  {
    "name": "setSelection",
    "aliases": [
      "selection.set"
    ],
    "required": "shape-dependent coordinates (`rect`/`ellipse`: `x,y,width,height`; `polygon`: `points[3+]`)",
    "supportedArgs": "`shape`, `type`, `x`, `y`, `left`, `top`, `width`, `height`, `points`, `mode`, `feather`, `antiAlias`",
    "example": "{\n  \"op\": \"setSelection\",\n  \"shape\": \"rect\",\n  \"x\": 120,\n  \"y\": 120,\n  \"width\": 600,\n  \"height\": 320\n}"
  },
  {
    "name": "modifySelection",
    "aliases": [
      "selection.modify"
    ],
    "required": "`mode` plus mode-specific args (`expand`/`contract`: `by`; `feather`/`smooth`: `radius`; `grow`: `by` or `tolerance`)",
    "supportedArgs": "`mode`, `by`, `radius`, `tolerance`, `applyEffectAtCanvasBounds`",
    "example": "{\n  \"op\": \"modifySelection\",\n  \"mode\": \"expand\",\n  \"by\": 10\n}"
  },
  {
    "name": "createLayerMask",
    "aliases": [
      "layerMask.create"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`forceBatchPlay`, `fromSelection`, `hideAll`",
    "example": "{\n  \"op\": \"createLayerMask\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"fromSelection\": true\n}"
  },
  {
    "name": "addLayerMask",
    "aliases": [
      "layerMask.add"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`forceBatchPlay`, `fromSelection`, `hideAll`",
    "example": "{\n  \"op\": \"addLayerMask\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"fromSelection\": true\n}"
  },
  {
    "name": "deleteLayerMask",
    "aliases": [
      "layerMask.delete"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`apply`, `forceBatchPlay`",
    "example": "{\n  \"op\": \"deleteLayerMask\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"apply\": false\n}"
  },
  {
    "name": "removeLayerMask",
    "aliases": [
      "layerMask.remove"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "`apply`, `forceBatchPlay`",
    "example": "{\n  \"op\": \"removeLayerMask\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"apply\": false\n}"
  },
  {
    "name": "applyLayerMask",
    "aliases": [
      "layerMask.apply"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"applyLayerMask\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  }\n}"
  },
  {
    "name": "createAdjustmentLayer",
    "aliases": [
      "adjustment.create"
    ],
    "required": "None (`levels` default when omitted)",
    "supportedArgs": "`adjustment`, `name`, `type`",
    "example": "{\n  \"op\": \"createAdjustmentLayer\",\n  \"type\": \"brightnessContrast\",\n  \"adjustment\": {\n    \"brightness\": 10,\n    \"contrast\": 5\n  },\n  \"name\": \"Grade\"\n}"
  },
  {
    "name": "applyFilter",
    "aliases": [
      "filter.apply"
    ],
    "required": "`filter (or kind)`",
    "supportedArgs": "`filter`, `kind`",
    "example": "{\n  \"op\": \"applyFilter\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"filter\": \"gaussianBlur\",\n  \"radius\": 4\n}"
  },
  {
    "name": "applyGaussianBlur",
    "aliases": [
      "filter.gaussianBlur"
    ],
    "required": "`target (or active layer)`, `radius`",
    "supportedArgs": "`radius`",
    "example": "{\n  \"op\": \"applyGaussianBlur\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"radius\": 3\n}"
  },
  {
    "name": "applyUnsharpMask",
    "aliases": [
      "filter.unsharpMask"
    ],
    "required": "`target (or active layer)`, `amount, radius, threshold`",
    "supportedArgs": "`amount`, `radius`, `threshold`",
    "example": "{\n  \"op\": \"applyUnsharpMask\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"amount\": 80,\n  \"radius\": 1.5,\n  \"threshold\": 2\n}"
  },
  {
    "name": "applySharpen",
    "aliases": [
      "filter.sharpen"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"applySharpen\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  }\n}"
  },
  {
    "name": "applyBlur",
    "aliases": [
      "filter.blur"
    ],
    "required": "`target (or active layer)`",
    "supportedArgs": "No op-specific args",
    "example": "{\n  \"op\": \"applyBlur\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  }\n}"
  },
  {
    "name": "createTextLayer",
    "aliases": [
      "text.create"
    ],
    "required": "`text (or contents)`",
    "supportedArgs": "`avoidOverlapWith`, `contents`, `docRef`, `ellipsis`, `font`, `fontName`, `fontSize`, `hardMinFontSize`, `maxHeight`, `maxWidth`, `minFontSize`, `name`, `overflow`, `overflowMode`, `overlapGap`, `position`, `text`",
    "example": "{\n  \"op\": \"createTextLayer\",\n  \"name\": \"Headline\",\n  \"text\": \"Summer Launch\",\n  \"fontSize\": 72,\n  \"position\": {\n    \"x\": 96,\n    \"y\": 220\n  }\n}"
  },
  {
    "name": "setText",
    "aliases": [
      "text.set"
    ],
    "required": "`target (or active layer)`, `text (or contents)`",
    "supportedArgs": "`contents`, `text`",
    "example": "{\n  \"op\": \"setText\",\n  \"target\": {\n    \"layerName\": \"Headline\"\n  },\n  \"text\": \"New headline copy\"\n}"
  },
  {
    "name": "setTextStyle",
    "aliases": [
      "text.style"
    ],
    "required": "`target (or active layer)`, `at least one style/content field`",
    "supportedArgs": "`avoidOverlapWith`, `contents`, `ellipsis`, `font`, `fontName`, `fontSize`, `hardMinFontSize`, `maxHeight`, `maxWidth`, `minFontSize`, `overflow`, `overflowMode`, `overlapGap`, `position`, `text`",
    "example": "{\n  \"op\": \"setTextStyle\",\n  \"target\": {\n    \"layerName\": \"Headline\"\n  },\n  \"font\": \"Avenir Next\",\n  \"fontSize\": 64,\n  \"maxWidth\": 860,\n  \"overflow\": \"resize\"\n}"
  },
  {
    "name": "createShapeLayer",
    "aliases": [
      "shape.create"
    ],
    "required": "`bounds or x/y/width/height`",
    "supportedArgs": "`bounds`, `color`, `fill`, `height`, `name`, `shape`, `shapeType`, `width`, `x`, `y`",
    "example": "{\n  \"op\": \"createShapeLayer\",\n  \"name\": \"CTA Button\",\n  \"shape\": \"rectangle\",\n  \"x\": 88,\n  \"y\": 980,\n  \"width\": 320,\n  \"height\": 92,\n  \"fill\": \"#2563eb\"\n}"
  },
  {
    "name": "export",
    "aliases": [
      "document.export",
      "render"
    ],
    "required": "`output`",
    "supportedArgs": "`docRef`, `target`, `output`, `format`, `quality`, `metadata`, `sRGB`, `options`",
    "example": "{\n  \"op\": \"export\",\n  \"output\": \"./tmp/frame.png\",\n  \"format\": \"png\",\n  \"quality\": 90\n}"
  },
  {
    "name": "exportDocument",
    "aliases": [
      "document.exportDocument"
    ],
    "required": "`output`",
    "supportedArgs": "`docRef`, `output`, `format`, `quality`, `metadata`, `sRGB`, `options`",
    "example": "{\n  \"op\": \"exportDocument\",\n  \"output\": \"./tmp/document.png\",\n  \"format\": \"png\"\n}"
  },
  {
    "name": "exportLayer",
    "aliases": [
      "document.exportLayer"
    ],
    "required": "`target (or active layer)`, `output`",
    "supportedArgs": "`target`, `docRef`, `output`, `format`, `quality`, `metadata`, `sRGB`, `options`",
    "example": "{\n  \"op\": \"exportLayer\",\n  \"target\": {\n    \"layerName\": \"Hero\"\n  },\n  \"output\": \"./tmp/hero.png\",\n  \"format\": \"png\"\n}"
  },
  {
    "name": "exportLayersByName",
    "aliases": [
      "document.exportLayersByName"
    ],
    "required": "`match`, `outputDir (or output)`",
    "supportedArgs": "`docRef`, `format`, `match`, `output`, `outputDir`",
    "example": "{\n  \"op\": \"exportLayersByName\",\n  \"match\": \"^(Hero|CTA)$\",\n  \"format\": \"png\",\n  \"outputDir\": \"./tmp/layers\"\n}"
  },
  {
    "name": "batchPlay",
    "aliases": [
      "action.batchPlay"
    ],
    "required": "`commands[] or command/descriptor`",
    "supportedArgs": "`allowUnavailable`, `command`, `commands`, `descriptor`, `options`",
    "example": "{\n  \"op\": \"batchPlay\",\n  \"commands\": [\n    {\n      \"_obj\": \"get\",\n      \"_target\": [\n        {\n          \"_ref\": \"document\",\n          \"_enum\": \"ordinal\",\n          \"_value\": \"targetEnum\"\n        }\n      ]\n    }\n  ]\n}"
  }
] as const;
